# Generated by Django 2.2.3 on 2019-07-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
